### PR TITLE
Adds support for Skype through MicrosoftSkypeMiddleware

### LINKED ISSUE #31: Support Skype
Should this provide support for Skype ?

I've created [this repo](https://github.com/leonardochaia/hubot-botframework-skype) I'm using for internal bots inspired on the MSTeamsMiddleware.
Any chance we could extract the relevant logic of the MSTeamsMiddleware so it can be shared for Skype and MS Teams?

Thanks,
Leo.

### PR DESCRIPTION
**Pull request by leonardochaia**
Adds the `MicrosoftSkypeMiddleware`, which is the same as the `MicrosoftTeamsMiddleware` but with less features.

Features included:

1. Typing indicator support
2. Properly handles chat vs. channel messages
3. Properly handles image responses.

Features removed:
1. Slack mentions convertion
2. `HUBOT_OFFICE365_TENANT_FILTER `

Given that the logic below `Helper methods for generating richer messages` (line 70) is exactly the same as `MicrosoftTeamsMiddleware` we could refactor to reuse it, but considering that, despite of being the same, they're specific to the channel they represent so we may decide to leave it as it is.
Do let me know if you'd like to share this logic and I'll refactor.

Fixes #31

### CODE REVIEW

**Comment by MattSFT** [comment]
Just call it the SkypeMiddleware. The Teams one is called MicrosoftTeamsMiddleware because that's technically the full product name.

**Comment by leonardochaia** [comment]
@MattSFT done, renamed `MicrosoftSkypeMiddleware` to `SkypeMiddleware`

**Comment by MattSFT** [comment]
@leonardochaia are you planning to merge this in?

**Comment by leonardochaia** [comment]
Hi @MattSFT, it'd be great to merge this, but I don't think I'm allowed to:

> Only those with write access to this repository can merge pull requests.

**Pull request merged**
